res = dict(p_load_grid=np.array([power_grid["load"][z][t].X for t in time_steps]),
               p_inj_grid=np.array([power_grid["inj"][z][t].X  for t in time_steps]),
               p_load_P2P_Ges=np.array([power_P2P_sum["load"][z][t].X  for t in time_steps]),
               p_inj_P2P_Ges=np.array([power_P2P_sum["inj"][z][t].X for t in time_steps]),
                p_inj_P2P=np.array([power_P2P["inj"][z][j][t].X  for j in nodes for t in time_steps]),
                p_load_P2P=np.array([power_P2P["load"][z][j][t].X  for j in nodes for t in time_steps]),
                power={dev: np.array([power_dom[dev][z][t].X for t in time_steps]) for dev in ["HP", "EB", "PV"]},
                heat={dev: np.array([heat_dom[dev][z][t].X for t in time_steps]) for dev in ["HP", "EB"]},
                soc={dev: np.array([soc_dom[dev][z][t].X for t in time_steps]) for dev in ["TES", "BAT", "EV"]},
                ch={dev: np.array([ch_dom[device][z][t].X for t in time_steps]) for dev in ["TES", "BAT", "EV"]},
                dch={dev: np.array([dch_dom[device][z][t].X for t in time_steps]) for dev in ["TES", "BAT", "EV"]},
                p_use= np.array([res_dom["power"][z][t].X for t in time_steps]),
                p_sell= np.array([res_dom["feed"][z][t].X for t in time_steps]))

res = dict(p_load_grid=np.array([power_grid["load"][z][t].X for t in time_steps]),
               p_inj_grid=np.array([power_grid["inj"][z][t].X  for t in time_steps]),
               p_load_P2P_Ges=np.array([power_P2P_sum["load"][z][t].X  for t in time_steps]),
               p_inj_P2P_Ges=np.array([power_P2P_sum["inj"][z][t].X for t in time_steps]),
                p_inj_P2P=np.array([power_P2P["inj"][z][j][t].X  for j in nodes for t in time_steps]),
                p_load_P2P=np.array([power_P2P["load"][z][j][t].X  for j in nodes for t in time_steps]),
                power={dev: np.array([power_dom[dev][z][t].X for t in time_steps]) for dev in ["HP", "EB", "PV"]},
                heat={dev: np.array([heat_dom[dev][z][t].X for t in time_steps]) for dev in ["HP", "EB"]},
                soc={dev: np.array([soc_dom[dev][z][t].X for t in time_steps]) for dev in ["TES", "BAT", "EV"]},
                ch={dev: np.array([ch_dom[device][z][t].X for t in time_steps]) for dev in ["TES", "BAT", "EV"]},
                dch={dev: np.array([dch_dom[device][z][t].X for t in time_steps]) for dev in ["TES", "BAT", "EV"]},
                p_use= np.array([res_dom["power"][z][t].X for t in time_steps]),
                p_sell= np.array([res_dom["feed"][z][t].X for t in time_steps]))